//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityRepositoryPatterns.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public long BookID { get; set; }
        public string BookName { get; set; }
        public string Descrption { get; set; }
        public decimal Price { get; set; }
        public long AutherID { get; set; }
        public long TagID { get; set; }
    
        public virtual Auther Auther { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
